# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: lorisleiva/laravel-docker:7.3
    steps:
      - run: composer create-project --prefer-dist laravel/laravel app "5.8.*"
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "app/composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: cd app && composer require lucascudo/laravel-pt-br-localization
      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-{{ checksum "app/composer.json" }}
      - run: cd app && php artisan vendor:publish --tag=laravel-pt-br-localization
      - run: "[ -f app/resources/lang/pt-BR/auth.php ]"
      - run: "[ -f app/resources/lang/pt-BR/pagination.php ]"
      - run: "[ -f app/resources/lang/pt-BR/passwords.php ]"
      - run: "[ -f app/resources/lang/pt-BR/validation.php ]"
      